package com.fnwd.nrreborn.datagen;

import com.fnwd.nrreborn.NuclearRelativisticsReborn;
import com.fnwd.nrreborn.block.NRRBlocks;
import com.fnwd.nrreborn.item.NRRItems;
import com.fnwd.nrreborn.util.CTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class NRRItemTagProvider extends ItemTagsProvider {
    public NRRItemTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, CompletableFuture<TagLookup<Block>> blockTags, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, blockTags, NuclearRelativisticsReborn.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        tag(CTags.Items.INGOTS)
                .add(NRRItems.TIN_INGOT.get())
                .add(NRRItems.ALUMINUM_INGOT.get())
                .add(NRRItems.SILVER_INGOT.get())
                .add(NRRItems.LEAD_INGOT.get())
                .add(NRRItems.MAGNESIUM_INGOT.get())
                .add(NRRItems.LITHIUM_INGOT.get())
                .add(NRRItems.BORON_INGOT.get())
                .add(NRRItems.BERYLLIUM_INGOT.get())
                .add(NRRItems.ZIRCONIUM_INGOT.get())
                .add(NRRItems.THORIUM_INGOT.get())
                .add(NRRItems.URANIUM_INGOT.get())
                .add(NRRItems.THORIUM_OXIDE_INGOT.get())
                .add(NRRItems.URANIUM_OXIDE_INGOT.get())
                .add(NRRItems.MANGANESE_INGOT.get())
                .add(NRRItems.MANGANESE_OXIDE_INGOT.get())
                .add(NRRItems.MANGANESE_DIOXIDE_INGOT.get())
                .add(NRRItems.GRAPHITE_INGOT.get())
                .add(NRRItems.BRONZE_INGOT.get())
                .add(NRRItems.STEEL_INGOT.get())
                .add(NRRItems.FERROBORON_ALLOY_INGOT.get())
                .add(NRRItems.TOUGH_ALLOY_INGOT.get())
                .add(NRRItems.EXTREME_ALLOY_INGOT.get())
                .add(NRRItems.THERMOCONDUCTING_ALLOY_INGOT.get())
                .add(NRRItems.HARD_CARBON_ALLOY_INGOT.get())
                .add(NRRItems.SHIBUICHI_ALLOY_INGOT.get())
                .add(NRRItems.TIN_SILVER_ALLOY_INGOT.get())
                .add(NRRItems.LEAD_PLATINUM_ALLOY_INGOT.get())
                .add(NRRItems.ZIRCALOY_INGOT.get())
                .add(NRRItems.HSLA_STEEL_INGOT.get())
                .add(NRRItems.MAGNESIUM_DIBORIDE_ALLOY_INGOT.get())
                .add(NRRItems.LITHIUM_MANGANESE_DIOXIDE_ALLOY_INGOT.get())
                .add(NRRItems.SILICON_CARBIDE_INGOT.get())
                .add(NRRItems.SIC_SIC_CERAMIC_MATRIX_COMPOSITE.get());
        tag(CTags.Items.GEMS)
                .add(NRRItems.RHODOCHROSITE.get())
                .add(NRRItems.CUBIC_BORON_NITRIDE.get())
                .add(NRRItems.FLUORITE.get())
                .add(NRRItems.VILLIAUMITE.get())
                .add(NRRItems.CAROBBIITE.get())
                .add(NRRItems.BORON_ARSENIDE.get());
        tag(CTags.Items.DUSTS)
                .add(NRRItems.TIN_DUST.get())
                .add(NRRItems.ALUMINUM_DUST.get())
                .add(NRRItems.SILVER_DUST.get())
                .add(NRRItems.LEAD_DUST.get())
                .add(NRRItems.MAGNESIUM_DUST.get())
                .add(NRRItems.LITHIUM_DUST.get())
                .add(NRRItems.BORON_DUST.get())
                .add(NRRItems.BERYLLIUM_DUST.get())
                .add(NRRItems.ZIRCONIUM_DUST.get())
                .add(NRRItems.THORIUM_DUST.get())
                .add(NRRItems.URANIUM_DUST.get())
                .add(NRRItems.THORIUM_OXIDE_DUST.get())
                .add(NRRItems.URANIUM_OXIDE_DUST.get())
                .add(NRRItems.MANGANESE_DUST.get())
                .add(NRRItems.MANGANESE_OXIDE_DUST.get())
                .add(NRRItems.MANGANESE_DIOXIDE_DUST.get())
                .add(NRRItems.GRAPHITE_DUST.get())
                .add(NRRItems.COAL_DUST.get())
                .add(NRRItems.DIAMOND_DUST.get())
                .add(NRRItems.QUARTZ_DUST.get())
                .add(NRRItems.OBSIDIAN_DUST.get())
                .add(NRRItems.END_STONE_DUST.get())
                .add(NRRItems.SULFUR_DUST.get())
                .add(NRRItems.RHODOCHROSITE_DUST.get())
                .add(NRRItems.HEXAGONAL_BORON_NITRIDE.get())
                .add(NRRItems.FLUORITE_DUST.get())
                .add(NRRItems.VILLIAUMITE_DUST.get())
                .add(NRRItems.CAROBBIITE_DUST.get())
                .add(NRRItems.ARSENIC_DUST.get())
                .add(NRRItems.ALUGENTUM_DUST.get())
                .add(NRRItems.BORAX.get())
                .add(NRRItems.CALCIUM_SULFATE.get())
                .add(NRRItems.SODIUM_FLUORIDE.get())
                .add(NRRItems.POTASSIUM_FLUORIDE.get())
                .add(NRRItems.SODIUM_HYDROXIDE.get())
                .add(NRRItems.POTASSIUM_HYDROXIDE.get());
        tag(CTags.Items.RAW_MATERIALS)
                .add(NRRItems.RAW_TIN.get())
                .add(NRRItems.RAW_LEAD.get())
                .add(NRRItems.RAW_MAGNESIUM.get())
                .add(NRRItems.RAW_LITHIUM.get())
                .add(NRRItems.RAW_BORON.get())
                .add(NRRItems.RAW_THORIUM.get())
                .add(NRRItems.RAW_URANIUM.get());
        tag(CTags.Items.ORES)
                .add(NRRBlocks.TIN_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_TIN_ORE.asItem())
                .add(NRRBlocks.LEAD_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_LEAD_ORE.asItem())
                .add(NRRBlocks.MAGNESIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_MAGNESIUM_ORE.asItem())
                .add(NRRBlocks.LITHIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_LITHIUM_ORE.asItem())
                .add(NRRBlocks.BORON_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_BORON_ORE.asItem())
                .add(NRRBlocks.THORIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_THORIUM_ORE.asItem())
                .add(NRRBlocks.URANIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_URANIUM_ORE.asItem());
        tag(CTags.Items.INGOTS_TIN).add(NRRItems.TIN_INGOT.get());
        tag(CTags.Items.INGOTS_ALUMINUM).add(NRRItems.ALUMINUM_INGOT.get());
        tag(CTags.Items.INGOTS_SILVER).add(NRRItems.SILVER_INGOT.get());
        tag(CTags.Items.INGOTS_LEAD).add(NRRItems.LEAD_INGOT.get());
        tag(CTags.Items.INGOTS_MAGNESIUM).add(NRRItems.MAGNESIUM_INGOT.get());
        tag(CTags.Items.INGOTS_LITHIUM).add(NRRItems.LITHIUM_INGOT.get());
        tag(CTags.Items.INGOTS_BORON).add(NRRItems.BORON_INGOT.get());
        tag(CTags.Items.INGOTS_BERYLLIUM).add(NRRItems.BERYLLIUM_INGOT.get());
        tag(CTags.Items.INGOTS_ZIRCONIUM).add(NRRItems.ZIRCONIUM_INGOT.get());
        tag(CTags.Items.INGOTS_THORIUM).add(NRRItems.THORIUM_INGOT.get());
        tag(CTags.Items.INGOTS_URANIUM).add(NRRItems.URANIUM_INGOT.get());
        tag(CTags.Items.INGOTS_THORIUM_OXIDE).add(NRRItems.THORIUM_OXIDE_INGOT.get());
        tag(CTags.Items.INGOTS_URANIUM_OXIDE).add(NRRItems.URANIUM_OXIDE_INGOT.get());
        tag(CTags.Items.INGOTS_MANGANESE).add(NRRItems.MANGANESE_INGOT.get());
        tag(CTags.Items.INGOTS_MANGANESE_OXIDE).add(NRRItems.MANGANESE_OXIDE_INGOT.get());
        tag(CTags.Items.INGOTS_MANGANESE_DIOXIDE).add(NRRItems.MANGANESE_DIOXIDE_INGOT.get());
        tag(CTags.Items.INGOTS_GRAPHITE).add(NRRItems.GRAPHITE_INGOT.get());
        tag(CTags.Items.INGOTS_BRONZE).add(NRRItems.BRONZE_INGOT.get());
        tag(CTags.Items.INGOTS_STEEL).add(NRRItems.STEEL_INGOT.get());
        tag(CTags.Items.INGOTS_FERROBORON_ALLOY).add(NRRItems.FERROBORON_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_TOUGH_ALLOY).add(NRRItems.TOUGH_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_EXTREME_ALLOY).add(NRRItems.EXTREME_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_THERMOCONDUCTING_ALLOY).add(NRRItems.THERMOCONDUCTING_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_HARD_CARBON_ALLOY).add(NRRItems.HARD_CARBON_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_SHIBUICHI_ALLOY).add(NRRItems.SHIBUICHI_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_TIN_SILVER_ALLOY).add(NRRItems.TIN_SILVER_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_LEAD_PLATINUM_ALLOY).add(NRRItems.LEAD_PLATINUM_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_ZIRCALOY).add(NRRItems.ZIRCALOY_INGOT.get());
        tag(CTags.Items.INGOTS_HSLA_STEEL).add(NRRItems.HSLA_STEEL_INGOT.get());
        tag(CTags.Items.INGOTS_MAGNESIUM_DIBORIDE_ALLOY).add(NRRItems.MAGNESIUM_DIBORIDE_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_LITHIUM_MANGANESE_DIOXIDE_ALLOY).add(NRRItems.LITHIUM_MANGANESE_DIOXIDE_ALLOY_INGOT.get());
        tag(CTags.Items.INGOTS_SILICON_CARBIDE).add(NRRItems.SILICON_CARBIDE_INGOT.get());
        tag(CTags.Items.INGOTS_SIC_SIC_CERAMIC_MATRIX_COMPOSITE).add(NRRItems.SIC_SIC_CERAMIC_MATRIX_COMPOSITE.get());
        tag(CTags.Items.GEMS_RHODOCHROSITE).add(NRRItems.RHODOCHROSITE.get());
        tag(CTags.Items.GEMS_CUBIC_BORON_NITRIDE).add(NRRItems.CUBIC_BORON_NITRIDE.get());
        tag(CTags.Items.GEMS_FLUORITE).add(NRRItems.FLUORITE.get());
        tag(CTags.Items.GEMS_VILLIAUMITE).add(NRRItems.VILLIAUMITE.get());
        tag(CTags.Items.GEMS_CAROBBIITE).add(NRRItems.CAROBBIITE.get());
        tag(CTags.Items.GEMS_BORON_ARSENIDE).add(NRRItems.BORON_ARSENIDE.get());
        tag(CTags.Items.SILICON).add(NRRItems.SILICON.get());
        tag(CTags.Items.DUSTS_TIN).add(NRRItems.TIN_DUST.get());
        tag(CTags.Items.DUSTS_ALUMINUM).add(NRRItems.ALUMINUM_DUST.get());
        tag(CTags.Items.DUSTS_SILVER).add(NRRItems.SILVER_DUST.get());
        tag(CTags.Items.DUSTS_LEAD).add(NRRItems.LEAD_DUST.get());
        tag(CTags.Items.DUSTS_MAGNESIUM).add(NRRItems.MAGNESIUM_DUST.get());
        tag(CTags.Items.DUSTS_LITHIUM).add(NRRItems.LITHIUM_DUST.get());
        tag(CTags.Items.DUSTS_BORON).add(NRRItems.BORON_DUST.get());
        tag(CTags.Items.DUSTS_BERYLLIUM).add(NRRItems.BERYLLIUM_DUST.get());
        tag(CTags.Items.DUSTS_ZIRCONIUM).add(NRRItems.ZIRCONIUM_DUST.get());
        tag(CTags.Items.DUSTS_THORIUM).add(NRRItems.THORIUM_DUST.get());
        tag(CTags.Items.DUSTS_URANIUM).add(NRRItems.URANIUM_DUST.get());
        tag(CTags.Items.DUSTS_THORIUM_OXIDE).add(NRRItems.THORIUM_OXIDE_DUST.get());
        tag(CTags.Items.DUSTS_URANIUM_OXIDE).add(NRRItems.URANIUM_OXIDE_DUST.get());
        tag(CTags.Items.DUSTS_MANGANESE).add(NRRItems.MANGANESE_DUST.get());
        tag(CTags.Items.DUSTS_MANGANESE_OXIDE).add(NRRItems.MANGANESE_OXIDE_DUST.get());
        tag(CTags.Items.DUSTS_MANGANESE_DIOXIDE).add(NRRItems.MANGANESE_DIOXIDE_DUST.get());
        tag(CTags.Items.DUSTS_GRAPHITE).add(NRRItems.GRAPHITE_DUST.get());
        tag(CTags.Items.DUSTS_COAL).add(NRRItems.COAL_DUST.get());
        tag(CTags.Items.DUSTS_DIAMOND).add(NRRItems.DIAMOND_DUST.get());
        tag(CTags.Items.DUSTS_QUARTZ).add(NRRItems.QUARTZ_DUST.get());
        tag(CTags.Items.DUSTS_OBSIDIAN).add(NRRItems.OBSIDIAN_DUST.get());
        tag(CTags.Items.DUSTS_END_STONE).add(NRRItems.END_STONE_DUST.get());
        tag(CTags.Items.DUSTS_SULFUR).add(NRRItems.SULFUR_DUST.get());
        tag(CTags.Items.DUSTS_RHODOCHROSITE).add(NRRItems.RHODOCHROSITE_DUST.get());
        tag(CTags.Items.DUSTS_HEXAGONAL_BORON_NITRIDE).add(NRRItems.HEXAGONAL_BORON_NITRIDE.get());
        tag(CTags.Items.DUSTS_FLUORITE).add(NRRItems.FLUORITE_DUST.get());
        tag(CTags.Items.DUSTS_VILLIAUMITE).add(NRRItems.VILLIAUMITE_DUST.get());
        tag(CTags.Items.DUSTS_CAROBBIITE).add(NRRItems.CAROBBIITE_DUST.get());
        tag(CTags.Items.DUSTS_ARSENIC).add(NRRItems.ARSENIC_DUST.get());
        tag(CTags.Items.DUSTS_ALUGENTUM).add(NRRItems.ALUGENTUM_DUST.get());
        tag(CTags.Items.DUSTS_BORAX).add(NRRItems.BORAX.get());
        tag(CTags.Items.DUSTS_CALCIUM_SULFATE).add(NRRItems.CALCIUM_SULFATE.get());
        tag(CTags.Items.DUSTS_SODIUM_FLUORIDE).add(NRRItems.SODIUM_FLUORIDE.get());
        tag(CTags.Items.DUSTS_POTASSIUM_FLUORIDE).add(NRRItems.POTASSIUM_FLUORIDE.get());
        tag(CTags.Items.DUSTS_SODIUM_HYDROXIDE).add(NRRItems.SODIUM_HYDROXIDE.get());
        tag(CTags.Items.DUSTS_POTASSIUM_HYDROXIDE).add(NRRItems.POTASSIUM_HYDROXIDE.get());
        tag(CTags.Items.RAW_MATERIALS_TIN).add(NRRItems.RAW_TIN.get());
        tag(CTags.Items.RAW_MATERIALS_LEAD).add(NRRItems.RAW_LEAD.get());
        tag(CTags.Items.RAW_MATERIALS_MAGNESIUM).add(NRRItems.RAW_MAGNESIUM.get());
        tag(CTags.Items.RAW_MATERIALS_LITHIUM).add(NRRItems.RAW_LITHIUM.get());
        tag(CTags.Items.RAW_MATERIALS_BORON).add(NRRItems.RAW_BORON.get());
        tag(CTags.Items.RAW_MATERIALS_THORIUM).add(NRRItems.RAW_THORIUM.get());
        tag(CTags.Items.RAW_MATERIALS_URANIUM).add(NRRItems.RAW_URANIUM.get());
        tag(CTags.Items.ORES_TIN)
                .add(NRRBlocks.TIN_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_TIN_ORE.asItem());
        tag(CTags.Items.ORES_LEAD)
                .add(NRRBlocks.LEAD_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_LEAD_ORE.asItem());
        tag(CTags.Items.ORES_MAGNESIUM)
                .add(NRRBlocks.MAGNESIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_MAGNESIUM_ORE.asItem());
        tag(CTags.Items.ORES_LITHIUM)
                .add(NRRBlocks.LITHIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_LITHIUM_ORE.asItem());
        tag(CTags.Items.ORES_BORON)
                .add(NRRBlocks.BORON_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_BORON_ORE.asItem());
        tag(CTags.Items.ORES_THORIUM)
                .add(NRRBlocks.THORIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_THORIUM_ORE.asItem());
        tag(CTags.Items.ORES_URANIUM)
                .add(NRRBlocks.URANIUM_ORE.asItem())
                .add(NRRBlocks.DEEPSLATE_URANIUM_ORE.asItem());
    }
}
